<?php

$settings = [
    'date' => [
        'Y-m-d' =>  'Y-m-d',
        'Y-d-m' =>  'Y-d-m',
        'Y/m/d' =>  'Y/m/d',
        'Y/d/m' =>  'Y/d/m',
        'd-m-Y' =>  'd-m-Y',
        'm-d-Y' =>  'm-d-Y',
        'd/m/Y' =>  'd/m/Y',
        'm/d/Y' =>  'm/d/Y',
        'F j, Y'    =>  'F j, Y',
        'j F, Y'    =>  'j F, Y',
        'M j, Y'    =>  'M j, Y',
        'j M, Y'    =>  'j M, Y',
    ],
    'time' => [
        'H:i' =>  'H:i',
        'h:i'   =>  'h:i',
        'H:i a'   =>  'H:i a',
        'h:i a'   =>  'h:i a',
    ],
    'datetime' => [
        'Y-m-d H:i' =>  'Y-m-d H:i',
        'Y-m-d h:i'   =>  'Y-m-d h:i',
        'Y-m-d H:i a' =>  'Y-m-d H:i a',
        'Y-m-d h:i a'   =>  'Y-m-d h:i a',
        'Y-d-m H:i' =>  'Y-d-m H:i',
        'Y-d-m h:i' =>  'Y-d-m h:i',
        'Y-d-m H:i a'   =>  'Y-d-m H:i a',
        'Y-d-m h:i a'   =>  'Y-d-m h:i a',
        'Y/m/d H:i' =>  'Y/m/d H:i',
        'Y/m/d h:i' =>  'Y/m/d h:i',
        'Y/m/d H:i a'   =>  'Y/m/d H:i a',
        'Y/m/d h:i a'   =>  'Y/m/d h:i a',
        'Y/d/m H:i' =>  'Y/d/m H:i',
        'Y/d/m h:i' =>  'Y/d/m h:i',
        'Y/d/m H:i a'   =>  'Y/d/m H:i a',
        'Y/d/m h:i a'   =>  'Y/d/m h:i a',
        'd-m-Y H:i' =>  'd-m-Y H:i',
        'd-m-Y h:i' =>  'd-m-Y h:i',
        'd-m-Y h:i a'   =>  'd-m-Y h:i a',
        'd-m-Y H:i a'   =>  'd-m-Y H:i a',
        'm-d-Y H:i' =>  'm-d-Y H:i',
        'm-d-Y h:i' =>  'm-d-Y h:i',
        'm-d-Y H:i a'   =>  'm-d-Y H:i a',
        'm-d-Y h:i a'   =>  'm-d-Y h:i a',
        'd/m/Y H:i' =>  'd/m/Y H:i',
        'd/m/Y h:i' =>  'd/m/Y h:i',
        'd/m/Y H:i a'   =>  'd/m/Y H:i a',
        'd/m/Y h:i a'   =>  'd/m/Y h:i a',
        'm/d/Y H:i' =>  'm/d/Y H:i',
        'm/d/Y h:i' =>  'm/d/Y h:i',
        'm/d/Y H:i a'   =>  'm/d/Y H:i a',
        'm/d/Y h:i a'   =>  'm/d/Y h:i a',
        'F j, Y, H:i'   =>  'F j, Y, H:i',
        'F j, Y, h:i'   =>  'F j, Y, h:i',
        'F j, Y, H:i a' =>  'F j, Y, H:i a',
        'F j, Y, h:i a' =>  'F j, Y, h:i a',
        'j F, Y, H:i'   =>  'j F, Y, H:i',
        'j F, Y, h:i'   =>  'j F, Y, h:i',
        'j F, Y, H:i a' =>  'j F, Y, H:i a',
        'j F, Y, h:i a' =>  'j F, Y, h:i a',
        'M j, Y, H:i'   =>  'M j, Y, H:i',
        'M j, Y, h:i'   =>  'M j, Y, h:i',
        'M j, Y, H:i a' =>  'M j, Y, H:i a',
        'M j, Y, h:i a' =>  'M j, Y, h:i a',
        'j M, Y, H:i'   =>  'j M, Y, H:i',
        'j M, Y, h:i'   =>  'j M, Y, h:i',
        'j M, Y, h:i a' =>  'j M, Y, h:i a',
        'j M, Y, H:i a' =>  'j M, Y, H:i a',
    ],
    'pagination'   =>  [
        '10'    =>  '10',
        '20'    =>  '20',
        '50'    =>  '50',
        '100'   =>  '100',
        '200'   =>  '200',
        '500'   =>  '500',
    ],
];

return $settings;